version: '2'
services:
  aoc:
    image: python:3.5
    volumes:
      - ./:/src
    working_dir: /src

  taxione:
    extends:
      service: aoc
    command: python -m one.ex1
  taxionetest:
    extends:
      service: aoc
    command: python -m one.test Test20160101
  taxitwo:
    extends:
      service: aoc
    command: python -m one.ex2
  taxitwotest:
    extends:
      service: aoc
    command: python -m one.test Test20160102

  bathroomsecurityone:
    extends:
      service: aoc
    command: python -m two.ex1
  bathroomsecurityonetest:
    extends:
      service: aoc
    command: python -m two.test Test20160201
  bathroomsecuritytwo:
    extends:
      service: aoc
    command: python -m two.ex2
  bathroomsecuritytwotest:
    extends:
      service: aoc
    command: python -m two.test Test20160202

  #day 3
  triangleone:
    extends:
      service: aoc
    command: python -m three.ex1
  triangleonetest:
    extends:
      service: aoc
    command: python -m three.test Test20160301
  triangletwo:
    extends:
      service: aoc
    command: python -m three.ex2
  triangletwotest:
    extends:
      service: aoc
    command: python -m three.test Test20160302

  #day 4
  securityone:
    extends:
      service: aoc
    command: python -m four.ex --part=1
  securityonetest:
    extends:
      service: aoc
    command: python -m four.test Test20160401
  securitytwo:
    extends: 
      service: aoc
    command: python -m four.ex --part=2
  securitytwotest:
    extends:
      service: aoc
    command: python -m four.test Test20160402

  #day 5
  day5one:
    extends:
      service: aoc
    command: python -m five.ex --part=1
  day5onetest:
    extends:
      service: aoc
    command: python -m five.test Test20160501
  day5two:
    extends: 
      service: aoc
    command: python -m five.ex --part=2
  day5twotest:
    extends:
      service: aoc
    command: python -m five.test Test20160502
