version: '2'
services:
  aoc:
    image: python:3.5
    volumes:
      - ./:/src
    working_dir: /src

  taxione:
    extends:
      service: aoc
    command: python -m one.ex1
  taxionetest:
    extends:
      service: aoc
    command: python -m one.test Test20160101
  taxitwo:
    extends:
      service: aoc
    command: python -m one.ex2
  taxitwotest:
    extends:
      service: aoc
    command: python -m one.test Test20160102

  bathroomsecurityone:
    extends:
      service: aoc
    command: python -m two.ex1
  bathroomsecurityonetest:
    extends:
      service: aoc
    command: python -m two.test Test20160201
  bathroomsecuritytwo:
    extends:
      service: aoc
    command: python -m two.ex2
  bathroomsecuritytwotest:
    extends:
      service: aoc
    command: python -m two.test Test20160202

  #day 3
  triangleone:
    extends:
      service: aoc
    command: python -m three.ex1
  triangleonetest:
    extends:
      service: aoc
    command: python -m three.test Test20160301
  triangletwo:
    extends:
      service: aoc
    command: python -m three.ex2
  triangletwotest:
    extends:
      service: aoc
    command: python -m three.test Test20160302

  #day 4
  securityone:
    extends:
      service: aoc
    command: python -m four.ex --part=1
  securityonetest:
    extends:
      service: aoc
    command: python -m four.test Test20160401
  securitytwo:
    extends: 
      service: aoc
    command: python -m four.ex --part=2
  securitytwotest:
    extends:
      service: aoc
    command: python -m four.test Test20160402

  #day 5
  day5one:
    extends:
      service: aoc
    command: python -m five.ex --part=1
  day5onetest:
    extends:
      service: aoc
    command: python -m five.test Test20160501
  day5two:
    extends: 
      service: aoc
    command: python -m five.ex --part=2
  day5twotest:
    extends:
      service: aoc
    command: python -m five.test Test20160502

  #day 6
  day6one:
    extends:
      service: aoc
    command: python -m six.ex --part=1
  day6onetest:
    extends:
      service: aoc
    command: python -m six.test Test20160601
  day6two:
    extends: 
      service: aoc
    command: python -m six.ex --part=2
  day6twotest:
    extends:
      service: aoc
    command: python -m six.test Test20160602
  day6test:
    extends:
      service: aoc
    command: python -m six.test

  #day 7
  day7one:
    extends:
      service: aoc
    command: python -m seven.ex --part=1
  day7onetest:
    extends:
      service: aoc
    command: python -m seven.test Test20160701
  day7two:
    extends: 
      service: aoc
    command: python -m seven.ex --part=2
  day7twotest:
    extends:
      service: aoc
    command: python -m seven.test Test20160702
  day7test:
    extends:
      service: aoc
    command: python -m seven.test

  #day 8
  day8one:
    extends:
      service: aoc
    command: python -m eight.ex --part=1
  day8onetest:
    extends:
      service: aoc
    command: python -m eight.test Test20160801
  day8two:
    extends: 
      service: aoc
    command: python -m eight.ex --part=2
  day8twotest:
    extends:
      service: aoc
    command: python -m eight.test Test20160802
  day8test:
    extends:
      service: aoc
    command: python -m eight.test

  #day 9
  day9one:
    extends:
      service: aoc
    command: python -m nine.ex --part=1
  day9onetest:
    extends:
      service: aoc
    command: python -m nine.test Test20160901
  day9two:
    extends: 
      service: aoc
    command: python -m nine.ex --part=2
  day9twotest:
    extends:
      service: aoc
    command: python -m nine.test Test20160902
  day9test:
    extends:
      service: aoc
    command: python -m nine.test

