version: '2'
services:
  aoc:
    image: python:3.5
    volumes:
      - ./:/src
    working_dir: /src

  taxione:
    extends:
      service: aoc
    command: python -m one.ex1
  taxionetest:
    extends:
      service: aoc
    command: python -m one.test Test20160101
  taxitwo:
    extends:
      service: aoc
    command: python -m one.ex2
  taxitwotest:
    extends:
      service: aoc
    command: python -m one.test Test20160102

  bathroomsecurityone:
    extends:
      service: aoc
    command: python -m two.ex1
  bathroomsecurityonetest:
    extends:
      service: aoc
    command: python -m two.test Test20160201
  bathroomsecuritytwo:
    extends:
      service: aoc
    command: python -m two.ex2
  bathroomsecuritytwotest:
    extends:
      service: aoc
    command: python -m two.test Test20160202
